kind: pipline
name: winsper-record

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package record-service completed 🙂🙂🙂"

  - name: upload_master
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      rm: true
      target: /Winsper/winsper-record
      source:
        - target/record-service-0.0.1-SNAPSHOT.jar
        - Dockerfile

  - name: make_image_and_copy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.98
      username: root
      script:
        - cd /Winsper/winsper-record/target
        - cp ../Dockerfile .
        - docker build -t winsper-record .
        - docker save winsper-record>winsper-record.tar
        - scp winsper-record.tar root@10.0.0.106:/root/Winsper/winsper-record
        - scp winsper-record.tar root@10.0.0.39:/root/Winsper/winsper-record
        - scp winsper-record.tar root@10.0.0.99:/root/Winsper/winsper-record

  - name: deploy_slave1
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.106
      username: root
      script:
        - cd /Winsper/winsper-record
        - docker load -i winsper-record.tar
        - docker rm -f winsper-record-c
        - docker run -d --name winsper-record-c --expose=7160 -p 7160:7160 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.106" -e "SERVER_PORT=7160" winsper-record

  - name: deploy_slave2
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.39
      username: root
      script:
        - cd /Winsper/winsper-record
        - docker load -i winsper-record.tar
        - docker rm -f winsper-record-c
        - docker run -d --name winsper-record-c --expose=7160 -p 7160:7160 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.39" -e "SERVER_PORT=7160" winsper-record

  - name: deploy_slave3
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.99
      username: root
      script:
        - cd /Winsper/winsper-record
        - docker load -i winsper-record.tar
        - docker rm -f winsper-record-c
        - docker run -d --name winsper-record-c --expose=7160 -p 7160:7160 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.99" -e "SERVER_PORT=7160" winsper-record




volumes:
  - name: dependency
    host:
      path: /root/.m2