kind: pipline
name: winsper-record

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package hean-service completed 🙂🙂🙂"
      
  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.41
      username: root
      key: 
        from_secret: private_key
      rm: true
      target: ~/tbc/drone/tmp
      source:
      - target/record-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.41
      username: root
      key: 
        from_secret: private_key
      command_timeout: 20m
      script:
      - cd ~/tbc/drone/tmp/target
      - cp ../Dockerfile .
      - docker build -t gusabary/winsper-record .
      - docker login
      - docker push gusabary/winsper-record
      - cd ~/tbc/Winsper
      - kubectl delete deploy/winsper-record
      - kubectl apply -f record-deployment.yml

volumes:
  - name: dependency
    host:
      path: /root/.m2
